// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kflxrkytvgbirjlbrvxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmbHhya3l0dmdiaXJqbGJydnh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MTc1MjYsImV4cCI6MjA2ODM5MzUyNn0.WevJqe5YUuHBiM1LkMSzObklpTOeb0Q3-TJuetnKDLE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});